### ISSUE TITLE
Prepare CGN dataset

### ISSUE THREAD

**Issue by fauxneticien** [fauxneticien/active_learning-w2v2_asr#1]
@Bartelds to prepare 5-hour dataset (3 hours training, 1 hour dev, 1 hour test) for experiments

**Comment by fauxneticien** [comment]
@Bartelds — can you also write a short description about the sampled subset?

> We sampled 5 hours from the 'read aloud text' subset of the CGN corpus (Component 14: Oostdijk, 2000), roughly balancing speakers according to metadata (e.g. gender), and ensuring no repeat in speakers between train, dev, and test splits

**Comment by Bartelds** [comment]
The 5-hour CGN dataset is now available in the Drive.

The data is randomly sampled from the component-o (i.e. read speech) data available in our processed version of the CGN corpus (see: https://martijnbartelds.nl/NAACL_2022.pdf).

The uploaded subset contains 3.02 hours training data (51% male, 49% female speakers), 1.01 hours dev data (50% male, 50% female speakers), and 1.01 hours test data (51% male and 49% female speakers).

**Comment by fauxneticien** [comment]
@clairezb — is that enough info? If not, just comment here to ask about specific details...
